version: '3'

services:
    node-app:
        container_name: myNodeApp
        restart: always
        build: ./
        ports:
            - "5000:8080"
        links: 
            - mongo


    mongo:
        container_name: myMongo
        image: mongo
        ports: 
            - "27017:27017"
    webserver:
        image: php:7.3-apache
        restart: always
        ports:
            - "14080:80"
        volumes:
            - ./:/var/www/html
            -  /srv/www/web_apps/test_https/apache_log:/var/log/apache2
